name: Presubmit Checks

on:
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 2 * * 0'  # Weekly

jobs:
  armv7-m:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/charlesnicholson/docker-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: arm-none-eabi-gcc -march=armv7-m -Os -Werror -Wall -Wextra -Wconversion -DNANOLOG_PROVIDE_ASSERT_MACROS=1 -c nanolog.c

  linux-gcc:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/charlesnicholson/docker-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        env:
          CC: /usr/bin/gcc
          CXX: /usr/bin/g++
        run: make -j

  linux-clang:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/charlesnicholson/docker-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
        run: make -j

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make -j

  win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call make-win.bat

  python:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/charlesnicholson/docker-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: cd pynanolog && python3 setup.py bdist_wheel
